# Generated by Django 3.2.11 on 2022-01-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category_id', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('barcode_num', models.PositiveIntegerField(unique=True)),
                ('seller', models.CharField(max_length=200)),
            ],
        ),
    ]
